// LinkType enum'unu merkezi olarak tanımlayalım
export type LinkType = 
  | "CUSTOM"
  | "INSTAGRAM" 
  | "TWITTER"
  | "FACEBOOK"
  | "YOUTUBE"
  | "TIKTOK"
  | "LINKEDIN"
  | "GITHUB"
  | "DISCORD"
  | "TELEGRAM"
  | "WHATSAPP"
  | "SPOTIFY"
  | "TWITCH"
  | "SNAPCHAT"
  | "PINTEREST"
  | "REDDIT"
  | "MEDIUM"
  | "BEHANCE"
  | "DRIBBBLE"
  | "WEBSITE"
